- CentOS-5/Dockerfile
This [warning](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-149/Polygon_mesh_processing/TestReport_lrineau_CentOS5.gz) should go away by this upgrade of Eigen.
> Upgrade Eigen from 3.2.5 to 3.2.8

- ArchLinux-CXX14/Dockerfile
- ArchLinux-clang-CXX14/Dockerfile
- ArchLinux-clang-CXX1z/Dockerfile
- ArchLinux-clang-Release/Dockerfile
- ArchLinux-clang-svn/Dockerfile
- ArchLinux-clang/Dockerfile
- ArchLinux/Dockerfile
NTL is from the official package repository, LEDA-free and RS from the public user repository (maintained by a colleague of mine and myself).
I just recognized that Philipp refrained from adding RS due to doubts about the licensing (#26). I think this is not a problem: according to personal communication with Fabrice Rouillier, the [RS license](http://vegas.loria.fr/rs/rslicense.txt) is meant to be "morally" LGPL2 (though I'm aware that it doesn't read that way). If you want formal consent by him, I suppose it's best to contact him immediately without me as a man-in-the-middle; I'm sure he'll grant it.
I'm less confident about the implications of Docker images with GPL'ed software, by the way, but I guess someone else thought about that already...
> Arch Linux: add NTL, LEDA-free and RS

- CentOS-6/Dockerfile
- CentOS-7/Dockerfile
- Debian-stable/Dockerfile
This PR fixes #46 .
It installs cmake 3.1.3 for Debian-stable and CentOs-6, and cmake 3.6.2 for CentOs-7.
> Install newest cmake

- Ubuntu-GCC6/Dockerfile
This fixes #51.
The repository address for gcc doesn't work anymore, so we use a github address instead.
> Fix Ubuntu-GCC6

- Ubuntu-clang-latest/Dockerfile
This PR proposes an ubuntu based image that installs the latest clang from trunk and use it as c and c++ compiler.
> Add an image to test the latest clang on Ubuntu.

- ArchLinux/Dockerfile
Fixes #50.
- lua52 -> lua as dependency for ipe
- make Dockerfile more stable w.r.t. directories if something breaks
- make images a tad smaller by removing package build files earlier
> Fixes for ArchLinux base Dockerfile

- Fedora-rawhide-fsanitize/Dockerfile
This PR fixes #57 .
It adds an image for Fedora-rawhide with the flags -fsanitize=address, -Og and -g.
> Add a new image with fsanitize=address

- CentOS-6-32/Dockerfile
This fixes the image CentOS-6 32bits, that still has a deprecated CMake.
> Fix centOs 6 32bits

- CentOS-5/Dockerfile
This fixes #62 
This PR upgrades cmake to 3.1.3.
> Upgrade CentOS-5 cmake version

- CentOS-7-ICC/Dockerfile
- CentOS-7-ICC/config.cfg
fixes #69 
A path to the license file may have to be given in the config file with the line 
ACTIVATION_LICENSE_FILE=\<path to file\>
> Install parallel studio 2017 on CentOS-7-ICC.

- ArchLinux/Dockerfile
Let's say all packages are actually optional.
> Try to fix build issues of ipe

- Debian-testing/Dockerfile
- Fedora-32/Dockerfile
- Fedora/Dockerfile
Until the server configuration allows to put them back. it should put R instead of N on all the demos.
> Remove qt5 from the platforms that don't support it on the server

- ArchLinux/Dockerfile
Fix Archlinux. Base it on archlinux/base:release and remove the pipe `yes` for pacman -Scc that returned an error.
> Fix for Archlinux images

- Debian-testing/Dockerfile
- Fedora-32/Dockerfile
- Fedora/Dockerfile
Reverts CGAL/cgal-testsuite-dockerfiles#86
I will the test of those platforms to renoir (Fedora 28).
> Revert "Remove qt5 from the platforms that don't support it on the server"

- Debian-stable/Dockerfile
Don't use cmake 3.4 in debian-stable, because it does not support ctest
> Use latest cmake in debian-stable

- Debian-stable/Dockerfile
Remove Qt from Debian-stable (version too old)
> Remove Qt from Debian-stable platforms

- Fedora/Dockerfile
Install lbssh in Fedora images to test the ssh feature in the demo.
> Add libssh-devel to Fedora

- Fedora-32/Dockerfile
- Fedora-rawhide/Dockerfile
- Fedora/Dockerfile
add diffutils in the installed pkgs of the Fedora images.
> Fix "diff missing command" issues on our Fedora images

- Ubuntu/Dockerfile
Resolved libpointmatcher build issue by installing yaml-cpp.
> Install yaml-cpp to fix libpointmatcher build error

- Ubuntu/Dockerfile
For the `Ubuntu` images (that are now [Ubuntu 24.04, aka Noble Numbat](https://releases.ubuntu.com/)), the `master` version of `libpointmatcher` does not work. See https://github.com/CGAL/cgal-testsuite-dockerfiles/actions/runs/9239645476/job/25419044232#step:3:10178
This PR switches to commit https://github.com/norlab-ulaval/libpointmatcher/commit/e9a832d, that is described by Git as `1.3.1-178-ge9a832d` (178 commits ahead of the tag `1.3.1`).
> do not test libpointmatcher `master`, but 1.3.1

- run-testsuite.sh
Useful for this PR: https://github.com/CGAL/cgal/pull/8254
> TestSuite: List of third-party libraries
