- CentOS-5/Dockerfile
I had put the hash tag of the beta-3 instead of 3.2.8 in the previous commit
> Change the directory  name of Eigen 3.2.8

- CentOS-7-ICC-2016/Dockerfile
This fixes #49 .
This needs to be tested with a license as I could not.
> Update ICC-2016 to version 4.

- Ubuntu-clang-latest/Dockerfile
Fixes the new ubuntu image, that were lacking two environnement variables.
> Fix for clang

- Ubuntu-clang-latest/Dockerfile
This PR removes the -g option.
> Accelerate the testsuite

- ArchLinux/Dockerfile
-> No need to workaround the issues with the old image.
> ArchLinux docker images are now updated daily

- Fedora/Dockerfile
- Ubuntu/Dockerfile
> Install opencv on Ubuntu and Fedora

- CentOS-7-ICC-2016/Dockerfile
- CentOS-7-ICC/Dockerfile
> Add a guard variable to avoid evaluating profile.d several times.

- ArchLinux/Dockerfile
- CentOS-6/Dockerfile
- CentOS-7/Dockerfile
- Debian-stable/Dockerfile
- Debian-testing/Dockerfile
- Fedora-32/Dockerfile
- Fedora-rawhide/Dockerfile
- Fedora/Dockerfile
- Ubuntu/Dockerfile
Add opensource TBB to base images of the testsuite.
> Add TBB to base images

- ArchLinux-clang-CXX14/Dockerfile
- ArchLinux-clang/Dockerfile
> Remove the -g flag in ArchLinux-clang and ArchLinux-clang-CXX14 images

- CentOS-7/Dockerfile
- Debian-stable/Dockerfile
> Add metis to Debian-stable and CentOs7

- Ubuntu/Dockerfile
All is in the title. 
fixes https://github.com/CGAL/cgal/issues/2893
> Add suitesparse to Ubuntu

- test_cgal.py
Parse the exitCode instead of the Status, as Status has changed and is useless now.
> Fix cgal_test.py for recent Docker

- Debian-stable/Dockerfile
Add cmake to the packages to be installed
> Fix debian-stable

- Debian-stable-cross-compilation-for-arm/startup.sh
> Update the image for cross compilation

- Debian-stable-cross-compilation-for-arm/startup.sh
Replace run_testsuite_with_cmake by run_testsuite_with_ctest in docker image's startup script.
> Update cross compilation image

- ArchLinux-CXX14/Dockerfile
> Make Archlinux-CXX a HEADER_ONLY=OFF platform

- run-testsuite.sh
export CGAL_RELEASE_DIR in the script
> Update script for cmake testsuite

- ArchLinux/Dockerfile
- Fedora/Dockerfile
- Ubuntu-clang-latest/Dockerfile
Use the fixed branch of lastools
> Update the LAStools branch

- .github/workflows/tests.yml
Notes:
- CentOS machines cannot find the 'base' repo during `yum update` 
- gcc_master did not build last time I checked
> Add a github workflow to replace the travis workflow

- .github/workflows/tests.yml
- ArchLinux/Dockerfile
- Fedora-rawhide/Dockerfile
Fedora rawhide rpm address is dead, use another one
> Replace dead URL

- Ubuntu/Dockerfile
> Install osqp on Ubuntu images

- Ubuntu/Dockerfile
> Add ITK to the ubuntu Images

- run-testsuite.sh
Needed for #4229 to handle .cmd files
> set CGAL_DATA_DIR

- Ubuntu/Dockerfile
Added soplex, scip and ceres-solver to Ubuntu dockerfile
Allows testing of Polygonal Surface Reconstruction and mesh smoothing in PMP
> added scip (incl. soplex) and ceres-solver libs

- Ubuntu/Dockerfile
Set MINIGLOG_MAX_LOG_LEVEL to 0 to suppress log spamming
> Reduce logging (Ceres)

- run-testsuite.sh
Useful for this PR: https://github.com/CGAL/cgal/pull/8188
> Add operating system info to test results file
